### ISSUE TITLE
Please evaluate OmegaConf and Hydra

### ISSUE THREAD

**Issue by omry** [pypyr/pypyr#194]
Hi, interesting project!
I am the author of  [OmegaConf](https://github.com/omry/omegaconf) and of [Hydra](https://hydra.cc).

Take a look at OmegaConf has some powerful features that can help your project:
- Config composition
- Interpolations
- Optional strong runtime type safety (via dataclasses).
And more.
 
Hydra could also be of interest, although some of it's default behaviors may be inappropriate for your proejct.

**Comment by yaythomas** [comment]
Thanks @omry. Especially the dot-list functionality is very interesting!

**Comment by omry** [comment]
The dotlist is one of the earlier features in OmegaConf :).
You have another task for schema validation which I think can be addressed easily using Structured Configs.
I am also sure interpolation can help you reduce config duplication (and can also allow transparent access to environment variables):
```
user: ${env:USER}
```

**Comment by yaythomas** [comment]
that really is very cool! amazing work, thanks for sharing!

**Comment by omry** [comment]
Glad you like it.
I strongly recommend that you look at Hydra as well, it's significantly more advanced but also more opinionated - and some of the opinions may be somewhat incompatible with your goals.
Let me know what you think.
