### ISSUE TITLE
Support for pyproject.toml

### ISSUE THREAD

**Issue by rr-** [pypyr/pypyr#231]
pypyr seems nice but polluting the filesystem with a few small files is the opposite of what I want from this tool, which is to replace makefiles such as this one:

```
test:
	pytest --cov=dict --cov-report term-missing

lint:
	pre-commit run -a

clean:
	rm .coverage
	rm -rf .mypy_cache
	rm -rf .pytest_cache

.PHONY: test lint clean
```

and on top of it, allow me to pass extra arguments to it so I can `make test my/test.py`, and use the now-standard pyproject.toml for it (just like setuptools has setup.py and npm has package.json).

**Comment by yaythomas** [comment]
thanks for the feedback @rr-!

Could you please help me understand better, because I'm not entirely clear on what you're suggesting? Do you mean that you would _not_ like to have yaml pipeline files and you instead want to define your step sequences in `pyproject.toml` itself?
