### ISSUE TITLE
RFE:  Add clipboard support to doc code snippets

### ISSUE THREAD

**Issue by cidrblock** [pypyr/pypyr#279]
Just trying this out for the first time, not sure what docs engine your are using, but clipboard/copy support in the docs would be super helpful to go through the tutorials

**Comment by yaythomas** [comment]
good idea, thanks @cidrblock! (The doc engine is Hugo, with a custom theme.) Should be able to get that done soon-ish.

**Comment by yaythomas** [comment]
done. I took a bit of time to make some custom icons & transitions to make it look nice - hope it helps (and looks good)!
