### ISSUE TITLE
`pypyr.steps.cmds` in `pypyr/pypyr-ops` docker image fails

### ISSUE THREAD

**Issue by Otard95** [pypyr/pypyr#343]
Hey.

I've been messing around with this tool and hope that I can use it to create a CI/CD system for my personal git server. And I prefer to put everything in docker containers on my homer server, so I've been using the `pypyr/pypyr-ops` docker image for all my testing.

I ran into this error:
```
The module doesn't exist. Looking for a file like this: pypyr.steps.cmds
Error at pipeline step pypyr.steps.cmds yaml line: 2, col: 3
Something went wrong. Will now try to run on_failure.

PyModuleNotFoundError: pypyr.steps.cmds.py should be in your working dir or it should be installed to the python path.
If you have 'package.sub.mod' your current working dir should contain ./package/sub/mod.py
If you specified 'mymodulename', your current working dir should contain ./mymodulename.py
If the module is not in your current working dir, it must exist in your current python path - so you should have run pip install or setup.py
```

When running `docker run -v ./:/src pypyr/pypyr-ops test-pipeline`. The pipeline in CWD is nothing special, it's just:
```
steps:
  - name: pypyr.steps.cmds
    in:
      cmds:
        - 'echo "Hello"'
        - 'echo "World"'
```

It is of course possible I've missed something in the docs. But I would expect this to work, as this is one of the "built-in" steps.

Really cool tool though, and I appreciate the work you put into it!

**Comment by yaythomas** [comment]
ah, sorry about that, the pypyr official docker images are fairly far behind with updates... they're still sitting on pypyr 4.5, `pypyr.steps.cmds` came in version 5.5, we're currently on 5.9.1....

stand by, will update.

**Comment by Otard95** [comment]
Ahh I see. Thanks for the clarification, and for updating the images 🙌. Again, really cool project, and great work!

**Comment by yaythomas** [comment]
thank you :-) 

pypyr-ops:7.0.0 is live... a docker pull should get you the latest.

**Comment by Otard95** [comment]
Amazing! Thanks a lot :smile:
